[14042022 15:38:58] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[14042022 15:38:58] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[14042022 15:40:03] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 15:41:02] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 15:42:02] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 15:43:02] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 15:44:03] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 15:45:03] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 15:46:01] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 15:46:46] connection /root/dionaea/src/connection_tcp.c:271-warning: recv failed size -1 recv_size 1 (Connection reset by peer)
[14042022 15:47:03] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 15:48:03] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 15:49:03] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 15:50:03] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 15:51:03] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 15:52:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 15:53:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 15:54:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 15:55:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 15:56:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 15:57:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 15:58:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 15:59:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 16:00:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 16:01:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 16:02:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 16:03:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 16:04:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 16:05:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 16:06:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 16:07:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 16:08:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 16:09:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 16:10:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 16:11:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 16:12:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 16:13:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 16:14:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 16:15:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 16:16:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 16:17:12] python /root/dionaea/modules/python/module.c:1039-warning: AttributeError at 'SipSession' object has no attribute 'apply_parent_config'
[14042022 19:35:23] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[14042022 19:35:23] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[14042022 19:38:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 19:41:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 19:46:52] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 19:48:54] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 19:48:54] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 19:48:54] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 19:48:54] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 19:48:54] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 19:48:54] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[14042022 19:48:54] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 19:48:54] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[14042022 19:48:54] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[14042022 19:48:54] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[14042022 19:48:54] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[14042022 19:48:54] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[14042022 19:48:54] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[14042022 19:48:54] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[14042022 20:43:47] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 20:43:47] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 20:43:47] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 20:43:47] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 20:43:47] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 20:43:47] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 20:43:47] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 20:43:47] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[14042022 20:43:47] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[14042022 20:43:47] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[14042022 20:43:47] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[14042022 20:43:47] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[14042022 20:43:47] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[14042022 20:43:47] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[14042022 20:43:47] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[14042022 20:43:47] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[14042022 20:43:47] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[14042022 20:43:47] mysqld /opt/dionaea/lib/dionaea/python/dionaea/mysql/mysql.py:83-warning: DATABASE opening information_schema
[14042022 20:43:47] mysqld /opt/dionaea/lib/dionaea/python/dionaea/mysql/mysql.py:86-warning: open db information_schema -> :memory:
[14042022 20:43:47] mysqld /opt/dionaea/lib/dionaea/python/dionaea/mysql/mysql.py:83-warning: DATABASE opening information_schema
[14042022 20:43:47] mysqld /opt/dionaea/lib/dionaea/python/dionaea/mysql/mysql.py:86-warning: open db information_schema -> :memory:
[14042022 20:43:47] mysqld /opt/dionaea/lib/dionaea/python/dionaea/mysql/mysql.py:83-warning: DATABASE opening information_schema
[14042022 20:43:47] mysqld /opt/dionaea/lib/dionaea/python/dionaea/mysql/mysql.py:86-warning: open db information_schema -> :memory:
[14042022 20:43:47] mysqld /opt/dionaea/lib/dionaea/python/dionaea/mysql/mysql.py:83-warning: DATABASE opening information_schema
[14042022 20:43:47] mysqld /opt/dionaea/lib/dionaea/python/dionaea/mysql/mysql.py:86-warning: open db information_schema -> :memory:
[14042022 20:43:47] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[14042022 20:43:47] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[14042022 20:43:47] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[14042022 20:43:47] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[14042022 20:43:47] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[14042022 20:43:47] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[14042022 20:43:47] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[14042022 20:43:47] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[14042022 20:43:47] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[14042022 20:43:47] python /root/dionaea/modules/python/module.c:1039-warning: AttributeError at 'SipSession' object has no attribute 'apply_parent_config'
[14042022 23:14:30] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[14042022 23:14:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[14042022 23:15:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 23:16:49] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 23:16:49] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 23:16:49] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[14042022 23:16:49] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[14042022 23:16:49] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[14042022 23:16:49] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[14042022 23:16:49] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[14042022 23:16:49] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[14042022 23:16:49] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[14042022 23:16:49] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[14042022 23:20:42] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[14042022 23:20:42] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[14042022 23:20:42] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[14042022 23:20:42] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[14042022 23:21:40] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 23:24:10] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 23:27:06] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 23:29:18] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 23:29:18] python /root/dionaea/modules/python/module.c:1039-warning: AttributeError at 'SipSession' object has no attribute 'apply_parent_config'
[14042022 23:32:38] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[14042022 23:32:38] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[14042022 23:33:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 23:34:34] python /root/dionaea/modules/python/module.c:1039-warning: AttributeError at 'SipSession' object has no attribute 'apply_parent_config'
[14042022 23:34:34] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[15042022 00:19:45] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[15042022 00:19:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[15042022 00:20:50] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[15042022 00:22:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[15042022 00:23:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[15042022 00:23:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[15042022 00:26:22] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[15042022 00:27:05] python /root/dionaea/modules/python/module.c:1039-warning: AttributeError at 'SipSession' object has no attribute 'apply_parent_config'
[15042022 03:25:42] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[15042022 03:25:42] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[15042022 03:26:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[15042022 03:27:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[15042022 03:30:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[15042022 03:32:10] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[15042022 03:33:41] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[15042022 03:33:41] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[15042022 03:39:45] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[15042022 03:39:45] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[15042022 03:39:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[15042022 03:39:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[15042022 03:39:45] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[15042022 03:39:45] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[15042022 03:39:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[15042022 03:48:36] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[15042022 03:48:36] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[15042022 03:48:36] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[15042022 03:48:36] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[15042022 03:48:36] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[15042022 03:48:36] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[15042022 03:48:36] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[15042022 03:48:36] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[15042022 03:48:36] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[15042022 03:48:36] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[15042022 03:48:36] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[15042022 03:48:36] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[15042022 03:48:36] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[15042022 03:50:08] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[15042022 03:50:08] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[15042022 03:54:17] python /root/dionaea/modules/python/module.c:1039-warning: AttributeError at 'SipSession' object has no attribute 'apply_parent_config'
[15042022 06:55:46] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[15042022 06:55:46] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[15042022 06:56:50] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[15042022 06:57:16] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[15042022 06:57:16] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[15042022 06:57:36] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[15042022 06:58:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[15042022 07:00:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[15042022 07:01:15] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[15042022 07:02:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[15042022 07:03:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[15042022 07:05:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[15042022 07:07:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[15042022 07:11:05] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[15042022 07:14:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[15042022 07:16:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[15042022 07:18:09] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[15042022 07:23:32] python /root/dionaea/modules/python/module.c:1039-warning: AttributeError at 'SipSession' object has no attribute 'apply_parent_config'
