[13042022 16:04:25] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[13042022 16:04:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[13042022 16:04:28] log /root/dionaea/src/signals.c:36-warning: sigterm_cb loop 0x7f516ca57720 w 0x55e831ec0230 revents 1024
[13042022 16:04:46] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[13042022 16:04:46] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[13042022 16:05:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 16:06:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 16:07:54] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 16:07:54] python /root/dionaea/modules/python/module.c:1039-warning: AttributeError at 'SipSession' object has no attribute 'apply_parent_config'
[13042022 16:11:06] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[13042022 16:11:06] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[13042022 16:12:05] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 16:13:05] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 16:14:05] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 16:15:05] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 16:16:05] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 16:17:05] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 16:18:05] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 16:19:05] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 16:19:10] python /root/dionaea/modules/python/module.c:1039-warning: AttributeError at 'SipSession' object has no attribute 'apply_parent_config'
[13042022 16:19:13] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[13042022 16:19:13] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[13042022 16:20:10] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 16:21:10] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 16:22:10] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 16:23:10] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 16:24:10] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 16:24:44] python /root/dionaea/modules/python/module.c:1039-warning: AttributeError at 'SipSession' object has no attribute 'apply_parent_config'
[13042022 16:24:46] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[13042022 16:24:46] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[13042022 16:25:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 16:26:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 16:27:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 16:28:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 16:29:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 16:30:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 16:31:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 16:32:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 16:33:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 16:34:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 16:35:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 16:36:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 16:37:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 16:38:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 16:39:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 16:40:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 16:41:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 16:42:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 16:44:05] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 16:45:51] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 16:45:51] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 16:45:51] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 18:22:59] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[13042022 18:22:59] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[13042022 18:22:59] python /root/dionaea/modules/python/module.c:1039-warning: AttributeError at 'SipSession' object has no attribute 'apply_parent_config'
[13042022 18:23:04] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[13042022 18:23:04] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[13042022 18:24:05] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 18:25:10] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 18:26:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 18:29:10] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 18:30:50] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 18:32:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 18:34:15] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 18:36:05] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 18:37:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 18:39:15] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 18:41:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 18:42:50] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 18:43:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 18:43:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 18:43:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 18:43:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 18:43:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 18:43:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 18:43:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 18:43:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 18:43:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 18:43:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 21:38:35] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[13042022 21:38:35] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[13042022 21:38:35] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[13042022 21:38:35] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[13042022 21:38:35] python /root/dionaea/modules/python/module.c:1039-warning: AttributeError at 'SipSession' object has no attribute 'apply_parent_config'
[13042022 21:38:41] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[13042022 21:38:41] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[13042022 21:40:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 21:42:05] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 21:44:41] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 21:46:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 21:47:10] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 21:48:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 21:49:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 21:51:05] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 21:53:05] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 21:54:04] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 21:54:04] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 21:54:04] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 23:11:26] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[13042022 23:11:26] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[13042022 23:11:26] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[13042022 23:11:26] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[13042022 23:11:26] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[13042022 23:11:26] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[13042022 23:11:26] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[13042022 23:11:26] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[13042022 23:11:26] python /root/dionaea/modules/python/module.c:1039-warning: AttributeError at 'SipSession' object has no attribute 'apply_parent_config'
[13042022 23:11:32] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[13042022 23:11:32] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[13042022 23:12:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 23:13:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 23:14:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 23:15:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 23:18:10] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 23:18:42] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 23:18:42] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 23:18:42] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 23:18:42] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 23:18:42] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 23:18:42] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 23:18:42] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[13042022 23:18:42] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[14042022 01:33:47] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[14042022 01:33:47] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[14042022 01:33:47] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[14042022 01:33:47] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[14042022 01:33:47] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[14042022 01:33:47] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[14042022 01:33:47] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[14042022 01:33:47] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[14042022 01:33:47] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[14042022 01:33:47] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[14042022 01:33:47] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[14042022 01:33:47] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[14042022 01:33:47] python /root/dionaea/modules/python/module.c:1039-warning: AttributeError at 'SipSession' object has no attribute 'apply_parent_config'
