[22042022 17:19:32] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[22042022 17:19:32] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[22042022 17:19:35] log /root/dionaea/src/signals.c:36-warning: sigterm_cb loop 0x7f641460f720 w 0x55c5ce7ce230 revents 1024
[22042022 17:19:55] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[22042022 17:19:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[22042022 17:20:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[22042022 17:21:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[22042022 17:22:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[22042022 17:23:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[22042022 17:24:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[22042022 17:25:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[22042022 17:26:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[22042022 17:27:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[22042022 17:28:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[22042022 17:29:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[22042022 17:30:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[22042022 17:31:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[22042022 17:32:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[22042022 17:33:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[22042022 17:34:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[22042022 17:35:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[22042022 17:36:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[22042022 17:37:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[22042022 17:38:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[22042022 17:39:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[22042022 17:40:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[22042022 17:41:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[22042022 17:42:09] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[22042022 17:42:09] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[22042022 17:42:37] connection /root/dionaea/src/connection_tcp.c:271-warning: recv failed size -1 recv_size 1 (Connection reset by peer)
[22042022 17:42:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[22042022 17:43:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[22042022 17:44:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[22042022 17:45:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[22042022 17:46:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[22042022 17:47:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[22042022 17:48:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[22042022 17:49:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[22042022 17:51:10] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[22042022 17:52:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[22042022 17:57:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[22042022 17:58:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[22042022 17:58:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[22042022 17:58:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[22042022 17:58:25] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[22042022 17:58:25] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[22042022 17:58:25] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[22042022 17:58:25] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[22042022 17:58:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[22042022 17:58:25] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[22042022 17:58:25] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[22042022 17:58:25] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[22042022 17:58:25] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[22042022 17:58:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[22042022 17:58:25] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[22042022 17:58:25] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[22042022 17:58:25] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[22042022 17:58:25] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[22042022 17:58:25] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[22042022 17:58:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[22042022 17:58:25] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[22042022 17:58:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[22042022 17:58:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[22042022 21:03:44] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[22042022 21:03:44] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[22042022 21:03:44] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[22042022 21:03:44] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[22042022 21:03:44] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[22042022 21:03:44] python /root/dionaea/modules/python/module.c:1039-warning: AttributeError at 'SipSession' object has no attribute 'apply_parent_config'
