[30042022 16:58:59] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[30042022 16:58:59] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[30042022 16:59:01] log /root/dionaea/src/signals.c:36-warning: sigterm_cb loop 0x7f411eab7720 w 0x55cf81110230 revents 1024
[30042022 16:59:21] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[30042022 16:59:21] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[30042022 17:00:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:01:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:02:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:02:52] SMB /opt/dionaea/lib/dionaea/python/dionaea/smb/smb.py:127-warning: p.haslayer(Raw): b'\x00\x00'
[30042022 17:02:52] SMB /opt/dionaea/lib/dionaea/python/dionaea/smb/smb.py:157-warning: p.haslayer(Raw): b'\x00\x00'
[30042022 17:03:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:04:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:05:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:06:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:07:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:08:20] mysqld /opt/dionaea/lib/dionaea/python/dionaea/mysql/mysql.py:83-warning: DATABASE opening information_schema
[30042022 17:08:20] mysqld /opt/dionaea/lib/dionaea/python/dionaea/mysql/mysql.py:86-warning: open db information_schema -> :memory:
[30042022 17:08:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:08:51] connection /root/dionaea/src/connection_tcp.c:271-warning: recv failed size -1 recv_size 1 (Connection reset by peer)
[30042022 17:09:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:10:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:11:06] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 17:11:06] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 17:11:24] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:12:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:12:37] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 17:12:37] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 17:13:14] tftp /opt/dionaea/lib/dionaea/python/dionaea/tftp.py:719-warning: Requested file /opt/dionaea/var/dionaea/roots/tftp/a.pdf does not exist.
[30042022 17:13:14] tftp /opt/dionaea/lib/dionaea/python/dionaea/tftp.py:723-warning: Requested file not found: /opt/dionaea/var/dionaea/roots/tftp/a.pdf
[30042022 17:13:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:13:56] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 17:13:56] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 17:14:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:15:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:16:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:17:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:18:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:19:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:20:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:21:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:22:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:23:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:24:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:25:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:26:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:27:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:28:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:29:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:29:43] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 17:29:43] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 17:30:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:31:04] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 17:31:04] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 17:31:04] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:31:04] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:31:04] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:31:04] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 17:31:04] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 17:31:04] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:31:04] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 17:31:04] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 17:31:04] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 19:10:06] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 19:10:06] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 19:10:06] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 19:10:06] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 19:10:06] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 19:10:06] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 19:10:06] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 19:10:06] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 19:10:06] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 19:10:06] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 19:10:06] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 19:10:06] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 19:10:06] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 19:10:06] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 19:10:06] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 19:10:06] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 19:10:06] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 19:10:06] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 19:10:13] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 19:10:13] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 19:11:06] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 19:11:06] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 19:11:06] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 19:11:06] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 19:11:06] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 20:07:43] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 20:07:43] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 20:07:43] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 20:07:43] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 20:07:43] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 20:07:43] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 20:07:43] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 20:07:43] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 20:07:43] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 20:07:43] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 20:07:43] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 20:07:43] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 20:07:43] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 20:07:43] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 20:07:43] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 20:07:43] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 20:07:43] python /root/dionaea/modules/python/module.c:1039-warning: AttributeError at 'SipSession' object has no attribute 'apply_parent_config'
[30042022 22:07:00] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[30042022 22:07:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[30042022 22:08:05] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 22:10:10] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 22:13:05] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 22:14:13] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 22:14:13] python /root/dionaea/modules/python/module.c:1039-warning: AttributeError at 'SipSession' object has no attribute 'apply_parent_config'
[30042022 22:15:04] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[30042022 22:15:04] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[30042022 22:16:15] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 22:17:51] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 22:17:51] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 22:17:51] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 22:17:51] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 22:17:51] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 22:17:51] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 22:17:51] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 22:17:51] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 22:17:51] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 22:17:51] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 22:17:51] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 22:17:51] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 22:17:51] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[30042022 22:17:51] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[30042022 22:17:51] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 22:17:51] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 22:17:51] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 22:17:51] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 22:17:51] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 22:17:51] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[30042022 22:17:51] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 00:42:28] python /root/dionaea/modules/python/module.c:1039-warning: AttributeError at 'SipSession' object has no attribute 'apply_parent_config'
[01052022 00:42:51] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[01052022 00:42:51] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[01052022 00:43:50] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 00:44:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 00:46:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 00:47:05] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 00:48:15] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 00:49:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 00:50:50] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 00:51:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 00:53:05] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 00:54:10] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 00:55:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 00:56:40] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 00:57:40] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 00:58:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 00:59:22] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 00:59:22] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 00:59:22] mysqld /opt/dionaea/lib/dionaea/python/dionaea/mysql/mysql.py:83-warning: DATABASE opening information_schema
[01052022 00:59:22] mysqld /opt/dionaea/lib/dionaea/python/dionaea/mysql/mysql.py:86-warning: open db information_schema -> :memory:
[01052022 00:59:22] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 00:59:22] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[01052022 00:59:22] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[01052022 00:59:22] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[01052022 00:59:22] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[01052022 00:59:22] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[01052022 00:59:22] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[01052022 00:59:22] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[01052022 00:59:22] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[01052022 01:02:57] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 01:05:22] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 01:06:27] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 01:06:27] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 01:06:27] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 01:06:27] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 01:06:27] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 01:06:27] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 01:06:27] mysqld /opt/dionaea/lib/dionaea/python/dionaea/mysql/mysql.py:83-warning: DATABASE opening information_schema
[01052022 01:06:27] mysqld /opt/dionaea/lib/dionaea/python/dionaea/mysql/mysql.py:86-warning: open db information_schema -> :memory:
[01052022 01:06:27] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 01:06:27] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[01052022 01:06:27] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[01052022 01:06:27] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[01052022 01:06:27] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[01052022 01:06:27] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 01:06:27] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[01052022 01:06:27] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[01052022 01:06:27] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[01052022 01:06:27] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[01052022 01:26:03] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 01:26:03] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 01:26:03] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 01:26:03] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 01:36:29] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[01052022 01:36:29] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[01052022 01:36:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 01:36:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 01:36:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 01:36:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 01:36:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 01:36:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 01:36:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 01:36:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 01:36:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 01:36:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 01:36:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 01:36:29] mysqld /opt/dionaea/lib/dionaea/python/dionaea/mysql/mysql.py:83-warning: DATABASE opening information_schema
[01052022 01:36:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 01:36:29] mysqld /opt/dionaea/lib/dionaea/python/dionaea/mysql/mysql.py:86-warning: open db information_schema -> :memory:
[01052022 01:36:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 01:36:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 01:36:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 01:36:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 01:36:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 01:36:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 04:21:01] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[01052022 04:21:01] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[01052022 04:21:01] python /root/dionaea/modules/python/module.c:1039-warning: AttributeError at 'SipSession' object has no attribute 'apply_parent_config'
[01052022 04:21:06] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[01052022 04:21:06] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[01052022 04:25:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 04:27:50] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 04:28:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 04:31:40] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 04:31:40] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 04:31:40] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 04:31:40] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 04:31:40] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[01052022 04:31:40] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[01052022 04:31:40] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[01052022 04:31:40] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[01052022 04:31:40] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[01052022 04:31:40] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[01052022 04:31:40] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[01052022 04:31:40] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[01052022 04:31:40] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[01052022 04:31:40] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[01052022 04:31:40] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[01052022 04:31:40] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[01052022 04:31:40] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[01052022 04:31:40] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[01052022 04:31:40] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[01052022 04:31:40] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[01052022 04:31:40] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[01052022 04:31:40] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[01052022 04:31:40] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[01052022 04:31:40] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[01052022 04:31:40] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[01052022 04:31:40] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[01052022 04:31:40] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[01052022 04:31:40] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[01052022 04:31:40] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[01052022 04:31:40] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[01052022 04:31:40] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[01052022 04:31:40] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[01052022 04:31:40] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[01052022 04:31:40] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[01052022 04:31:40] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[01052022 04:31:40] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[01052022 04:31:40] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[01052022 04:31:40] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[01052022 04:31:40] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[01052022 04:31:40] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[01052022 04:31:40] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[01052022 04:31:40] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[01052022 04:31:40] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[01052022 04:31:40] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[01052022 04:31:40] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[01052022 04:31:40] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[01052022 05:44:53] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[01052022 05:44:53] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[01052022 05:44:53] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[01052022 05:44:53] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[01052022 05:44:53] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[01052022 05:44:53] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[01052022 05:44:53] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[01052022 05:44:53] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[01052022 05:44:53] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[01052022 05:44:53] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[01052022 05:44:53] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[01052022 05:44:53] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[01052022 05:44:53] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[01052022 05:44:53] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[01052022 05:44:53] python /root/dionaea/modules/python/module.c:1039-warning: AttributeError at 'SipSession' object has no attribute 'apply_parent_config'
[01052022 05:44:58] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[01052022 05:44:58] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[01052022 05:46:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 05:47:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 05:48:05] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 05:49:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 05:51:05] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 05:57:53] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 06:06:46] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 06:16:06] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 06:25:16] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 06:34:41] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 06:44:01] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 06:54:09] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 07:01:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 07:02:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 07:03:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 07:05:05] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 07:06:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 07:07:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 07:09:05] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 07:10:50] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 07:12:50] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 07:14:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 07:16:05] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 07:17:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 07:18:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 07:19:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 07:20:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 07:21:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 07:22:50] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 07:24:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 07:25:50] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 07:27:40] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 07:29:40] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 07:31:15] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 07:33:15] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 07:35:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 07:36:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 07:39:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[01052022 07:41:05] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py: