[25042022 06:07:05] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[25042022 06:07:05] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[25042022 06:07:08] log /root/dionaea/src/signals.c:36-warning: sigterm_cb loop 0x7f815bba6720 w 0x55b253604230 revents 1024
[25042022 06:07:28] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[25042022 06:07:28] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[25042022 06:08:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:09:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:10:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:11:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:12:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:13:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:14:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:15:18] SMB /opt/dionaea/lib/dionaea/python/dionaea/smb/smb.py:127-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[25042022 06:15:18] SMB /opt/dionaea/lib/dionaea/python/dionaea/smb/smb.py:157-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[25042022 06:15:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:16:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:17:32] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:18:32] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:19:25] connection /root/dionaea/src/connection_tcp.c:271-warning: recv failed size -1 recv_size 1 (Connection reset by peer)
[25042022 06:19:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:20:05] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[25042022 06:20:05] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[25042022 06:20:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:20:58] SMB /opt/dionaea/lib/dionaea/python/dionaea/smb/smb.py:127-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[25042022 06:20:58] SMB /opt/dionaea/lib/dionaea/python/dionaea/smb/smb.py:157-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[25042022 06:21:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:22:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:22:46] connection /root/dionaea/src/connection_tcp.c:271-warning: recv failed size -1 recv_size 1 (Connection reset by peer)
[25042022 06:23:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:23:52] connection /root/dionaea/src/connection_tcp.c:271-warning: recv failed size -1 recv_size 1 (Connection reset by peer)
[25042022 06:23:55] connection /root/dionaea/src/connection_tcp.c:271-warning: recv failed size -1 recv_size 1 (Connection reset by peer)
[25042022 06:24:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:25:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:26:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:27:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:28:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:29:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:30:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:31:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:32:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:33:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:34:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:35:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:36:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:37:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:38:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:39:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:40:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:41:28] ftp /opt/dionaea/lib/dionaea/python/dionaea/ftp.py:235-warning: cmd 'b'AUTH''
[25042022 06:41:28] ftp /opt/dionaea/lib/dionaea/python/dionaea/ftp.py:235-warning: cmd 'b'AUTH''
[25042022 06:41:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:42:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:43:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:44:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:45:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:46:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:47:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:48:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:49:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:50:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:51:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:52:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:53:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:54:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:55:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:56:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:57:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:58:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 06:59:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 07:00:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 07:01:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 07:02:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 07:03:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 07:04:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 07:05:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 07:06:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 07:07:16] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[25042022 07:07:16] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[25042022 07:07:33] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 07:08:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 07:08:40] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[25042022 07:08:40] connection /root/dionaea/src/connection_tcp.c:271-warning: recv failed size -1 recv_size 1 (Connection reset by peer)
[25042022 07:09:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 07:10:13] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[25042022 07:10:13] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[25042022 07:10:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 07:11:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 07:12:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 07:13:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 07:14:19] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[25042022 07:14:19] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[25042022 07:14:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 07:15:33] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 07:16:15] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 07:16:15] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 07:16:15] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 07:16:15] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 07:16:15] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 07:16:15] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 10:08:20] mysqld /opt/dionaea/lib/dionaea/python/dionaea/mysql/mysql.py:83-warning: DATABASE opening information_schema
[25042022 10:08:20] mysqld /opt/dionaea/lib/dionaea/python/dionaea/mysql/mysql.py:86-warning: open db information_schema -> :memory:
[25042022 10:08:20] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[25042022 10:08:20] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[25042022 10:08:20] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[25042022 10:08:20] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[25042022 10:08:20] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[25042022 10:08:20] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[25042022 10:08:20] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[25042022 10:08:20] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[25042022 10:08:20] mysqld /opt/dionaea/lib/dionaea/python/dionaea/mysql/mysql.py:83-warning: DATABASE opening information_schema
[25042022 10:08:20] mysqld /opt/dionaea/lib/dionaea/python/dionaea/mysql/mysql.py:86-warning: open db information_schema -> :memory:
[25042022 10:08:20] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[25042022 10:08:20] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[25042022 10:08:20] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[25042022 10:08:20] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[25042022 10:08:20] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[25042022 10:08:20] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[25042022 10:08:20] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[25042022 10:08:20] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[25042022 10:08:20] python /root/dionaea/modules/python/module.c:1039-warning: AttributeError at 'SipSession' object has no attribute 'apply_parent_config'
[25042022 10:08:29] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[25042022 10:08:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[25042022 10:09:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 10:10:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 10:12:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 10:14:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 10:16:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 10:19:36] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 10:20:35] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[25042022 10:20:35] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[25042022 10:20:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 10:20:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 10:20:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 10:20:35] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[25042022 10:20:35] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[25042022 10:20:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 10:20:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 10:20:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 10:20:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 10:20:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 10:20:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 10:20:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 10:20:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 10:20:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 10:57:34] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 10:57:34] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 10:57:34] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 10:57:34] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 10:57:34] python /root/dionaea/modules/python/module.c:1039-warning: AttributeError at 'SipSession' object has no attribute 'apply_parent_config'
[25042022 12:29:43] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[25042022 12:29:43] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[25042022 12:29:43] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 12:29:43] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 12:29:43] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 12:35:52] python /root/dionaea/modules/python/module.c:1039-warning: AttributeError at 'SipSession' object has no attribute 'apply_parent_config'
[25042022 13:03:29] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[25042022 13:03:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[25042022 13:04:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 13:05:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 13:06:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 13:08:10] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 13:08:10] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[25042022 13:08:10] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[25042022 13:08:10] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 13:08:10] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[25042022 13:08:10] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[25042022 13:08:10] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 13:12:34] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 13:14:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 13:16:10] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[25042022 13:16:29] python /root/dionaea/modules/python/module.c:1039-warning: AttributeError at 'SipSession' object has no attribute 'apply_parent_config'
