[19042022 16:25:41] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[19042022 16:25:41] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[19042022 16:26:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 16:27:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 16:28:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 16:29:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 16:30:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 16:31:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 16:32:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 16:33:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 16:34:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 16:35:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 16:36:26] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[19042022 16:36:26] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[19042022 16:36:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 16:37:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 16:37:49] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[19042022 16:37:49] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[19042022 16:38:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 16:39:22] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[19042022 16:39:22] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[19042022 16:39:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 16:40:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 16:41:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 16:42:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 16:43:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 16:44:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 16:45:27] tftp /opt/dionaea/lib/dionaea/python/dionaea/tftp.py:719-warning: Requested file /opt/dionaea/var/dionaea/roots/tftp/a.pdf does not exist.
[19042022 16:45:27] tftp /opt/dionaea/lib/dionaea/python/dionaea/tftp.py:723-warning: Requested file not found: /opt/dionaea/var/dionaea/roots/tftp/a.pdf
[19042022 16:45:32] python /root/dionaea/modules/python/module.c:1039-warning: AttributeError at 'SipSession' object has no attribute 'apply_parent_config'
[19042022 16:45:36] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[19042022 16:45:36] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[19042022 16:46:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 16:47:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 16:48:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 16:49:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 16:50:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 16:51:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 16:51:51] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[19042022 16:51:51] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[19042022 16:51:57] connection /root/dionaea/src/connection_tcp.c:271-warning: recv failed size -1 recv_size 1 (Connection reset by peer)
[19042022 16:52:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 16:53:16] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[19042022 16:53:16] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[19042022 16:53:37] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 16:54:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 16:54:38] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[19042022 16:54:38] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[19042022 16:55:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 16:56:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 16:57:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 16:58:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 16:59:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 17:00:33] ftp /opt/dionaea/lib/dionaea/python/dionaea/ftp.py:235-warning: cmd 'b'AUTH''
[19042022 17:00:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 17:01:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 17:02:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 17:03:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 17:04:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 17:05:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 17:06:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 17:07:07] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[19042022 17:07:07] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[19042022 17:07:38] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 17:08:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 17:08:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 17:08:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 17:08:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 17:08:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 19:26:45] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[19042022 19:26:45] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[19042022 19:26:45] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[19042022 19:26:45] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[19042022 19:26:45] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[19042022 19:26:45] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[19042022 19:26:45] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[19042022 19:26:45] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[19042022 19:26:45] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[19042022 19:26:45] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[19042022 19:26:45] python /root/dionaea/modules/python/module.c:1039-warning: AttributeError at 'SipSession' object has no attribute 'apply_parent_config'
[19042022 19:26:50] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[19042022 19:26:50] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[19042022 19:27:50] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 19:29:05] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 19:30:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 19:32:15] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 19:33:30] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 19:34:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 19:36:51] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 19:41:06] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 19:45:35] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 19:49:05] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 19:50:52] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 19:50:52] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 19:59:42] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 19:59:42] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 19:59:42] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 19:59:42] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 19:59:42] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 19:59:42] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 22:02:19] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[19042022 22:02:19] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[19042022 22:02:19] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[19042022 22:02:19] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[19042022 22:02:19] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[19042022 22:02:19] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[19042022 22:02:19] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[19042022 22:02:19] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[19042022 22:02:19] mysqld /opt/dionaea/lib/dionaea/python/dionaea/mysql/mysql.py:83-warning: DATABASE opening information_schema
[19042022 22:02:19] mysqld /opt/dionaea/lib/dionaea/python/dionaea/mysql/mysql.py:86-warning: open db information_schema -> :memory:
[19042022 22:02:19] mysqld /opt/dionaea/lib/dionaea/python/dionaea/mysql/mysql.py:83-warning: DATABASE opening information_schema
[19042022 22:02:19] mysqld /opt/dionaea/lib/dionaea/python/dionaea/mysql/mysql.py:86-warning: open db information_schema -> :memory:
[19042022 22:03:15] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 22:04:15] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 22:10:04] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 22:10:04] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 22:10:04] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 22:10:04] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 22:10:04] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[19042022 22:10:04] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[19042022 23:46:16] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 23:46:16] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[19042022 23:46:16] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[19042022 23:46:16] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[19042022 23:46:16] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[19042022 23:46:16] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[19042022 23:46:16] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[19042022 23:46:16] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[19042022 23:46:16] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[19042022 23:46:16] python /root/dionaea/modules/python/module.c:1039-warning: AttributeError at 'SipSession' object has no attribute 'apply_parent_config'
[19042022 23:49:11] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[19042022 23:49:11] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[19042022 23:50:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 23:53:20] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 23:54:46] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[19042022 23:54:46] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 00:01:01] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 00:01:01] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 00:01:01] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 00:01:01] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 00:01:01] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 00:01:01] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 00:01:01] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 00:01:01] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 00:01:01] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 00:01:01] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 00:01:01] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 00:01:01] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 00:01:01] python /root/dionaea/modules/python/module.c:1039-warning: AttributeError at 'SipSession' object has no attribute 'apply_parent_config'
[20042022 03:00:55] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[20042022 03:00:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[20042022 03:01:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 03:02:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 03:03:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 03:05:10] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 03:10:46] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 03:13:28] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 03:13:28] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 03:13:28] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 03:13:28] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 03:13:28] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 03:13:28] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 06:19:55] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 06:19:55] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 06:19:55] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 06:19:55] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 06:19:55] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 06:19:55] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 06:19:55] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 06:19:55] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 06:19:55] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 06:19:55] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 06:19:55] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 06:19:55] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 06:19:55] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 06:19:55] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 06:19:55] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 06:19:55] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 06:19:55] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 06:19:55] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 06:19:55] python /root/dionaea/modules/python/module.c:1039-warning: AttributeError at 'SipSession' object has no attribute 'apply_parent_config'
[20042022 06:20:03] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[20042022 06:20:03] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[20042022 06:20:10] ftp /opt/dionaea/lib/dionaea/python/dionaea/ftp.py:235-warning: cmd 'b'AUTH''
[20042022 06:20:10] ftp /opt/dionaea/lib/dionaea/python/dionaea/ftp.py:235-warning: cmd 'b'AUTH''
[20042022 06:21:05] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 06:22:10] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 06:23:15] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 06:24:27] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 06:24:51] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 06:27:17] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 06:28:21] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 06:28:52] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 06:28:52] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 06:28:52] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 06:28:52] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 06:28:52] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 06:28:52] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 06:28:52] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 06:28:52] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 06:28:52] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 06:28:52] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 06:28:52] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 06:28:52] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 07:56:43] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 07:56:43] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 07:56:43] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 07:56:43] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 07:56:43] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 07:56:43] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 07:56:43] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 07:56:43] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 07:56:43] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 07:56:43] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 07:56:43] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 07:56:43] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 07:56:43] mysqld /opt/dionaea/lib/dionaea/python/dionaea/mysql/mysql.py:83-warning: DATABASE opening information_schema
[20042022 07:56:43] mysqld /opt/dionaea/lib/dionaea/python/dionaea/mysql/mysql.py:86-warning: open db information_schema -> :memory:
[20042022 07:56:43] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 07:56:43] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 07:56:43] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 07:56:43] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 07:56:43] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 07:56:43] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 07:56:43] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 07:56:43] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 07:56:43] mysqld /opt/dionaea/lib/dionaea/python/dionaea/mysql/mysql.py:83-warning: DATABASE opening information_schema
[20042022 07:56:43] mysqld /opt/dionaea/lib/dionaea/python/dionaea/mysql/mysql.py:86-warning: open db information_schema -> :memory:
[20042022 07:56:43] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 07:56:43] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 07:56:43] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 07:56:43] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 07:56:43] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 07:56:43] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 07:56:43] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 07:56:43] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 07:56:43] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 07:56:43] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 07:56:43] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 07:56:43] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 07:56:43] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 07:56:43] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 07:56:43] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 07:56:43] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 07:56:43] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 07:56:43] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 07:56:43] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 07:56:43] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 07:56:43] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 07:56:43] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 07:56:43] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 07:56:43] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 07:56:43] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 07:56:43] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 07:56:43] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 07:56:43] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 07:56:43] connection /root/dionaea/src/connection.c:137-warning: getpeername failed (Transport endpoint is not connected)
[20042022 07:56:43] connection /root/dionaea/src/connection_tcp.c:97-warning: accepting connection failed, closing connection
[20042022 07:56:43] python /root/dionaea/modules/python/module.c:1039-warning: AttributeError at 'SipSession' object has no attribute 'apply_parent_config'
[20042022 07:56:48] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[20042022 07:56:48] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[20042022 07:57:49] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 07:58:49] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 07:59:49] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:00:49] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:01:24] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:01:24] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:01:24] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:01:24] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:01:24] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:01:24] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:01:24] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:11:57] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:11:57] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:13:39] SMB /opt/dionaea/lib/dionaea/python/dionaea/smb/smb.py:127-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[20042022 08:13:39] SMB /opt/dionaea/lib/dionaea/python/dionaea/smb/smb.py:157-warning: p.haslayer(Raw): b'PATH_REPLACE__?????\x00'
[20042022 08:14:38] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:15:08] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:15:08] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:15:08] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:18:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:18:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:18:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:18:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:18:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:18:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:18:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:18:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:18:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:18:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:18:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:18:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:18:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:18:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:18:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:18:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:18:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:18:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:18:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:18:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:18:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:18:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:18:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:18:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:18:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:18:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:18:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:18:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:18:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:18:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:18:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:18:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:18:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:18:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:18:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:18:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:18:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:18:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:18:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:18:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:18:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:18:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:18:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:18:29] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 08:18:29] python /root/dionaea/modules/python/module.c:1039-warning: AttributeError at 'SipSession' object has no attribute 'apply_parent_config'
[20042022 11:55:19] dionaea /root/dionaea/src/dionaea.c:756-warning: Setgroups dropping groups failed
[20042022 11:55:19] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:78-warning: Starting cleanup loop
[20042022 11:55:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 11:55:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 11:55:25] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 12:03:44] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 12:04:32] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 12:05:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 12:06:56] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 12:07:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 12:08:55] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 12:09:54] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 12:11:00] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 12:11:45] sip /opt/dionaea/lib/dionaea/python/dionaea/sip/__init__.py:45-warning: Cleanup
[20042022 12:11:45] python /root/dionaea/modules/python/module.c:1039-warning: AttributeError at 'SipSession' object has no attribute 'apply_parent_config'
