2022-04-07 17:21:45,542 Config file found!
2022-04-07 17:21:45,549 Starting Conpot using template: /usr/lib/python3.9/site-packages/conpot/templates/guardian_ast
2022-04-07 17:21:45,550 Starting Conpot using configuration found in: /etc/conpot/conpot.cfg
2022-04-07 17:21:45,570 Serving tar:///usr/lib/python3.9/site-packages/conpot/data.tar as file system. File uploads will be kept at : /tmp/conpot
2022-04-07 17:21:45,571 Opening path /tmp/conpot for persistent storage of files.
2022-04-07 17:21:45,586 Initializing Virtual File System at /tmp/conpot/__conpot__tcsyyot4. Source specified : tar:///usr/lib/python3.9/site-packages/conpot/data.tar
 Please wait while the system copies all specified files
2022-04-07 17:21:45,858 Fetched 34.121.180.85 as external ip.
2022-04-07 17:21:45,862 Conpot GuardianAST initialized
2022-04-07 17:21:45,863 Found and enabled guardian_ast protocol.
2022-04-07 17:21:45,865 No proxy template found. Service will remain unconfigured/stopped.
2022-04-07 17:21:45,867 GuardianAST server started on: ('0.0.0.0', 10001)
2022-04-07 21:41:46,746 New guardian_ast session from 46.101.142.70 (3767f41b-7d9f-48ff-a6c2-2dab8621e196)
2022-04-07 21:50:54,006 New GuardianAST connection from 46.101.142.70:59470. (3767f41b-7d9f-48ff-a6c2-2dab8621e196)
2022-04-07 22:12:34,783 Non ^A command attempt 46.101.142.70:59470. (3767f41b-7d9f-48ff-a6c2-2dab8621e196)
2022-04-07 22:24:42,526 GuardianAST client disconnected 46.101.142.70:59470. (3767f41b-7d9f-48ff-a6c2-2dab8621e196)
2022-04-07 22:38:34,717 Session timed out: 3767f41b-7d9f-48ff-a6c2-2dab8621e196
2022-04-08 07:45:49,054 New guardian_ast session from 162.142.125.9 (4d61e1dd-93cc-4de5-94c2-8bf2a5db9208)
2022-04-08 07:54:27,095 New GuardianAST connection from 162.142.125.9:33294. (4d61e1dd-93cc-4de5-94c2-8bf2a5db9208)
2022-04-08 08:15:33,728 I20100 command attempt 162.142.125.9:33294. (4d61e1dd-93cc-4de5-94c2-8bf2a5db9208)
2022-04-08 08:28:39,470 Unknown Error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/conpot/protocols/guardian_ast/guardian_ast_server.py", line 497, in handle
    sock.send(str_to_bytes(response))
  File "/usr/lib/python3.9/site-packages/gevent/_socketcommon.py", line 722, in send
    return self._sock.send(data, flags)
ConnectionResetError: [Errno 104] Connection reset by peer
2022-04-08 08:28:41,000 GuardianAST client disconnected 162.142.125.9:33294. (4d61e1dd-93cc-4de5-94c2-8bf2a5db9208)
2022-04-08 08:28:41,039 New GuardianAST connection from 162.142.125.9:54860. (4d61e1dd-93cc-4de5-94c2-8bf2a5db9208)
2022-04-08 08:28:41,068 Unknown Error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/conpot/protocols/guardian_ast/guardian_ast_server.py", line 322, in handle
    request = sock.recv(4096)
  File "/usr/lib/python3.9/site-packages/gevent/_socketcommon.py", line 657, in recv
    return self._sock.recv(*args)
ConnectionResetError: [Errno 104] Connection reset by peer
2022-04-08 08:28:41,069 GuardianAST client disconnected 162.142.125.9:54860. (4d61e1dd-93cc-4de5-94c2-8bf2a5db9208)
2022-04-08 08:28:41,069 New GuardianAST connection from 162.142.125.9:47048. (4d61e1dd-93cc-4de5-94c2-8bf2a5db9208)
2022-04-08 08:28:41,070 Non ^A command attempt 162.142.125.9:47048. (4d61e1dd-93cc-4de5-94c2-8bf2a5db9208)
2022-04-08 08:28:41,070 GuardianAST client disconnected 162.142.125.9:47048. (4d61e1dd-93cc-4de5-94c2-8bf2a5db9208)
2022-04-08 08:28:41,070 New GuardianAST connection from 162.142.125.9:51374. (4d61e1dd-93cc-4de5-94c2-8bf2a5db9208)
2022-04-08 08:28:41,071 Non ^A command attempt 162.142.125.9:51374. (4d61e1dd-93cc-4de5-94c2-8bf2a5db9208)
2022-04-08 08:28:41,071 GuardianAST client disconnected 162.142.125.9:51374. (4d61e1dd-93cc-4de5-94c2-8bf2a5db9208)
2022-04-08 08:28:41,071 New GuardianAST connection from 162.142.125.9:47074. (4d61e1dd-93cc-4de5-94c2-8bf2a5db9208)
2022-04-08 08:28:41,072 Unknown Error: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/conpot/protocols/guardian_ast/guardian_ast_server.py", line 322, in handle
    request = sock.recv(4096)
  File "/usr/lib/python3.9/site-packages/gevent/_socketcommon.py", line 657, in recv
    return self._sock.recv(*args)
ConnectionResetError: [Errno 104] Connection reset by peer
2022-04-08 08:28:41,072 GuardianAST client disconnected 162.142.125.9:47074. (4d61e1dd-93cc-4de5-94c2-8bf2a5db9208)
2022-04-08 08:29:11,164 Session timed out: 4d61e1dd-93cc-4de5-94c2-8bf2a5db9208
